spring.application.name=eatBusan
spring.config.import=optional:file:.env[.properties]

# MySQL DataSource
spring.datasource.url=jdbc:mysql://localhost:3306/ssafydb?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#open api
data.api.baseurl=http://apis.data.go.kr
data.api.service.key=${DATA_API_KEY}